services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: ${CLICKHOUSE_HOST}
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PWORD}
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - data-network
    restart: always
    user: "${CLICKHOUSE_USER}:${CLICKHOUSE_USER}"

networks:
  data-network:
    name: ${NETWORK_NAME}
    driver: bridge

volumes:
  clickhouse_data: